name: chktex

on:
  pull_request:

jobs:
  chktex:
    name: chktex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install deps
        run: uv sync

      - name: Install chktex
        run: |
          sudo apt-get update
          sudo apt-get install -y chktex

      - name: Run chktex
        run: make chktex
