name: dotenv-linter
on: [pull_request]
jobs:
  dotenv-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install deps
        run: uv sync

      - name: Run dotenv-linter
        run: make dotenv-linter
