name: sql-check

on:
  pull_request:

jobs:
  sql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install deps
        run: uv sync

      - name: Apply schema.sql
        run: make run-schema
